import type { Quelle } from '../../domain/types.ts';

/**
 * Die Quellen, auf die sich die Faktenbasis stützt.
 *
 * Jeder Fakt verweist über `quelleId` hierher. Wo eine Norm kostenpflichtig
 * ist (VDE/DIN), steht die Verlagsseite als Bezugsnachweis; wo eine amtliche
 * Quelle frei zugänglich ist (Gesetze, DGUV, BAuA), steht der Direktlink.
 *
 * `geprueft` bedeutet: Titel, Kennung und Bezugsweg wurden am Original
 * abgeglichen (Abruf siehe `abgerufen`). Nicht geprüfte Quellen tragen
 * `geprueft: false` und werden im Bericht ausgewiesen.
 */
const ABGERUFEN = '2026-09-30';

export interface QuelleNachweis extends Quelle {
  /** true, wenn Titel, Kennung und Bezugsweg am Original geprüft wurden. */
  geprueft: boolean;
}

export const QUELLEN: Record<string, QuelleNachweis> = {
  elekausbv: {
    id: 'elekausbv',
    titel: 'Verordnung über die Berufsausbildung zum Elektroniker und zur Elektronikerin (ElekAusbV)',
    herausgeber: 'Bundesministerium für Wirtschaft und Klimaschutz',
    kennung: 'BGBl. I 2021 S. 662, 699 – Art. 4',
    ausgabe: '30.03.2021, gültig ab 01.08.2021',
    url: 'https://www.gesetze-im-internet.de/elekausbv/',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0100: {
    id: 'vde0100',
    titel: 'Errichten von Niederspannungsanlagen',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0100-410:2018-10, DIN VDE 0100-600:2017-06, DIN VDE 0100-100,-200,-430,-510,-701,-702,-710',
    ausgabe: 'Reihe DIN VDE 0100, Einzelteile mit eigenem Ausgabedatum',
    url: 'https://vde-verlag.de/p/normen/din-vde-0100-600-vde-0100-600-2017-06/0100382-DE-PR',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0105: {
    id: 'vde0105',
    titel: 'Betrieb von elektrischen Anlagen – Teil 100: Allgemeine Festlegungen',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0105-100:2015-10 (enthält EN 50110-1:2013), Änderung A1:2017-06',
    ausgabe: '2015-10',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0105-100/238330555',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0298: {
    id: 'vde0298',
    titel: 'Verwendung von Kabeln und isolierten Leitungen für Starkstromanlagen – Strombelastbarkeit',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0298-4:2013-06 (Neufassung 2023-06)',
    ausgabe: '2013-06',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0298-4/180878163',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0701: {
    id: 'vde0701',
    titel: 'Prüfung nach Instandsetzung, Änderung elektrischer Geräte – Wiederholungsprüfung elektrischer Geräte',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0701-0702:2008-06',
    ausgabe: '2008-06',
    url: 'https://vde-verlag.de/p/normen/din-vde-0701-0702-vde-0701-0702-2008-06/0701018-DE-PR',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  trbs1201: {
    id: 'trbs1201',
    titel: 'Prüfungen und Kontrollen von Arbeitsmitteln und überwachungsbedürftigen Anlagen (TRBS 1201)',
    herausgeber: 'Bundesanstalt für Arbeitsschutz und Arbeitsmedizin (BAuA), Ausschuss für Betriebssicherheit',
    kennung: 'TRBS 1201, Ausgabe März 2019, GMBl 2019 S. 229, zuletzt geändert GMBl 2025 S. 702',
    ausgabe: '2019-03',
    url: 'https://www.baua.de/DE/Angebote/Regelwerk/TRBS/TRBS-1201',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  dguv3: {
    id: 'dguv3',
    titel: 'Elektrische Anlagen und Betriebsmittel (Unfallverhütungsvorschrift)',
    herausgeber: 'Deutsche Gesetzliche Unfallversicherung (DGUV)',
    kennung: 'DGUV Vorschrift 3, Ausgabe April 1979, Fassung Januar 1997',
    ausgabe: '1997-01',
    url: 'https://publikationen.dguv.de/regelwerk/dguv-vorschriften/1052/elektrische-anlagen-und-betriebsmittel',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  dguv203072: {
    id: 'dguv203072',
    titel: 'Wiederkehrende Prüfungen elektrischer Anlagen und ortsfester Betriebsmittel – Fachwissen für Prüfpersonen',
    herausgeber: 'Deutsche Gesetzliche Unfallversicherung (DGUV)',
    kennung: 'DGUV Information 203-072 (Webcode p203072)',
    ausgabe: '2021-04',
    url: 'https://publikationen.dguv.de/regelwerk/dguv-informationen/2879/wiederkehrende-pruefungen-elektrischer-anlagen-und-ortsfester-betriebsmittel-fachwissen-fuer-pruefper',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  betrsichv: {
    id: 'betrsichv',
    titel: 'Verordnung über Sicherheit und Gesundheitsschutz bei der Verwendung von Arbeitsmitteln (Betriebssicherheitsverordnung – BetrSichV)',
    herausgeber: 'Bundesministerium der Justiz / Bundesamt für Justiz',
    kennung: 'BetrSichV, insbesondere § 14 (Prüfung von Arbeitsmitteln)',
    ausgabe: '2015, zuletzt geändert 2021',
    url: 'https://www.gesetze-im-internet.de/betrsichv_2015/__14.html',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  schultabelle: {
    id: 'schultabelle',
    titel: 'Strombelastbarkeitstabelle nach Berufsschul-/ZVEH-Systematik',
    herausgeber: 'ZVEH / Berufsschule',
    kennung: 'vereinfachte Absicherungswerte (kein Normwert)',
    ausgabe: null,
    url: null,
    abgerufen: ABGERUFEN,
    geprueft: false,
  },

  // --- Normen der Gebäudetechnik und des Anschlusses -----------------------
  vde0100_701: {
    id: 'vde0100_701',
    titel: 'Errichten von Niederspannungsanlagen – Anforderungen für Betriebsstätten, Räume und Anlagen besonderer Art – Badezimmer',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0100-701:2008-10',
    ausgabe: '2008-10',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0100-701/126467841',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0100_702: {
    id: 'vde0100_702',
    titel: 'Errichten von Niederspannungsanlagen – Schwimmbäder und andere Becken',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0100-702:2012-05',
    ausgabe: '2012-05',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0100-702/163452677',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0100_704: {
    id: 'vde0100_704',
    titel: 'Errichten von Niederspannungsanlagen – Baustellen und vergleichbare Bereiche',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0100-704:2018-10',
    ausgabe: '2018-10',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0100-704/290531507',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0100_705: {
    id: 'vde0100_705',
    titel: 'Errichten von Niederspannungsanlagen – Landwirtschaftliche und gartenbauliche Betriebsstätten',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0100-705:2007-10',
    ausgabe: '2007-10',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0100-705/109294316',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0100_712: {
    id: 'vde0100_712',
    titel: 'Errichten von Niederspannungsanlagen – Photovoltaik-Stromversorgungssysteme',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0100-712:2016-10',
    ausgabe: '2016-10',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0100-712/247301643',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0100_722: {
    id: 'vde0100_722',
    titel: 'Errichten von Niederspannungsanlagen – Stromversorgung von Elektrofahrzeugen',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0100-722:2019-06',
    ausgabe: '2019-06',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0100-722/304302470',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0100_530: {
    id: 'vde0100_530',
    titel: 'Errichten von Niederspannungsanlagen – Auswahl und Errichtung elektrischer Betriebsmittel – Schaltgeräte und Schaltverbindungen',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0100-530:2018-06',
    ausgabe: '2018-06',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0100-530/283106349',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0100_540: {
    id: 'vde0100_540',
    titel: 'Errichten von Niederspannungsanlagen – Erdungsanlagen, Schutzleiter und Schutzpotentialausgleichsleiter',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0100-540:2012-06',
    ausgabe: '2012-06',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0100-540/163453219',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0100_600: {
    id: 'vde0100_600',
    titel: 'Errichten von Niederspannungsanlagen – Prüfungen (Erstprüfung)',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0100-600:2017-06',
    ausgabe: '2017-06',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0100-600/270244275',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0105_100: {
    id: 'vde0105_100',
    titel: 'Betrieb von elektrischen Anlagen – Allgemeine Festlegungen',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0105-100:2015-10',
    ausgabe: '2015-10',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0105-100/238330555',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0298_4: {
    id: 'vde0298_4',
    titel: 'Verwendung von Kabeln und isolierten Leitungen – Strombelastbarkeit',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0298-4:2013-06',
    ausgabe: '2013-06',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0298-4/180878163',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0100_410: {
    id: 'vde0100_410',
    titel: 'Errichten von Niederspannungsanlagen – Schutzmaßnahmen – Schutz gegen elektrischen Schlag',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0100-410:2018-10',
    ausgabe: '2018-10',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0100-410/286120227',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0100_430: {
    id: 'vde0100_430',
    titel: 'Errichten von Niederspannungsanlagen – Schutzmaßnahmen – Schutz gegen Überstrom',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0100-430:2010-10',
    ausgabe: '2010-10',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0100-430/135790201',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0100_444: {
    id: 'vde0100_444',
    titel: 'Errichten von Niederspannungsanlagen – Schutzmaßnahmen – Schutz gegen elektromagnetische Störungen (EMV)',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0100-444:2010-10',
    ausgabe: '2010-10',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0100-444/135790237',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0100_510: {
    id: 'vde0100_510',
    titel: 'Errichten von Niederspannungsanlagen – Auswahl und Errichtung elektrischer Betriebsmittel – Allgemeine Regeln',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0100-510:2014-10',
    ausgabe: '2014-10',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0100-510/206240364',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0100_520: {
    id: 'vde0100_520',
    titel: 'Errichten von Niederspannungsanlagen – Auswahl und Errichtung elektrischer Betriebsmittel – Kabel und Leitungen',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0100-520:2013-06',
    ausgabe: '2013-06',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0100-520/180878171',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0100_443: {
    id: 'vde0100_443',
    titel: 'Errichten von Niederspannungsanlagen – Schutz bei Überspannungen',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0100-443:2016-10',
    ausgabe: '2016-10',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0100-443/248917421',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0100_534: {
    id: 'vde0100_534',
    titel: 'Errichten von Niederspannungsanlagen – Überspannungsschutzeinrichtungen',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0100-534:2016-10',
    ausgabe: '2016-10',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0100-534/248917429',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde0702: {
    id: 'vde0702',
    titel: 'Prüfung elektrischer Geräte – Wiederholungsprüfung',
    herausgeber: 'DIN VDE / VDE Verlag',
    kennung: 'DIN VDE 0702:2021-06',
    ausgabe: '2021-06',
    url: 'https://www.dinmedia.de/de/norm/din-vde-0702/330268289',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  vde_ar_n4105: {
    id: 'vde_ar_n4105',
    titel: 'Erzeugungsanlagen am Niederspannungsnetz – Technische Mindestanforderungen für Anschluss und Parallelbetrieb',
    herausgeber: 'VDE / FNN',
    kennung: 'VDE-AR-N 4105:2018-11',
    ausgabe: '2018-11',
    url: 'https://www.vde.com/de/fnn/arbeitsgebiete/na-schutz/erzeugungsanlagen',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  din_en_12831: {
    id: 'din_en_12831',
    titel: 'Heizungsanlagen in Gebäuden – Verfahren zur Berechnung der Norm-Heizlast',
    herausgeber: 'DIN / Beuth Verlag',
    kennung: 'DIN EN 12831-1:2017-09',
    ausgabe: '2017-09',
    url: 'https://www.beuth.de/de/norm/din-en-12831-1/270250540',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  din_v_18599: {
    id: 'din_v_18599',
    titel: 'Energetische Bewertung von Gebäuden – Berechnung des Nutz-, End- und Primärenergiebedarfs',
    herausgeber: 'DIN / Beuth Verlag',
    kennung: 'DIN V 18599-1:2018-09',
    ausgabe: '2018-09',
    url: 'https://www.beuth.de/de/norm/din-v-18599-1/287104852',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  din_en_50090: {
    id: 'din_en_50090',
    titel: 'Elektrische Systemtechnik für Heim und Gebäude (KNX)',
    herausgeber: 'DIN / Beuth Verlag',
    kennung: 'DIN EN 50090-Reihe, DIN EN 13321-1',
    ausgabe: 'Reihe',
    url: 'https://www.beuth.de/de/norm/din-en-50090-2-2/122805789',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  din_en_60204_1: {
    id: 'din_en_60204_1',
    titel: 'Sicherheit von Maschinen – Elektrische Ausrüstung von Maschinen',
    herausgeber: 'DIN / Beuth Verlag',
    kennung: 'DIN EN 60204-1:2019-06 (VDE 0113-1)',
    ausgabe: '2019-06',
    url: 'https://www.beuth.de/de/norm/din-en-60204-1/306735388',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  din_en_61439: {
    id: 'din_en_61439',
    titel: 'Niederspannungs-Schaltgerätekombinationen',
    herausgeber: 'DIN / Beuth Verlag',
    kennung: 'DIN EN 61439-Reihe (VDE 0660-600)',
    ausgabe: 'Reihe',
    url: 'https://www.beuth.de/de/norm/din-en-61439-1/347613976',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  taevo: {
    id: 'taevo',
    titel: 'Technische Anschlussbedingungen für den Anschluss an das Niederspannungsnetz (TAB)',
    herausgeber: 'VDE / FNN',
    kennung: 'TAR Niederspannung 2019',
    ausgabe: '2019',
    url: 'https://www.vde.com/de/fnn/arbeitsgebiete/tar',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  nav: {
    id: 'nav',
    titel: 'Verordnung über Allgemeine Bedingungen für den Netzanschluss und dessen Nutzung für die Elektrizitätsversorgung in Niederspannung',
    herausgeber: 'Bundesministerium der Justiz / Bundesamt für Justiz',
    kennung: 'NAV',
    ausgabe: '2006, zuletzt geändert 2023',
    url: 'https://www.gesetze-im-internet.de/nav/',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  eeg: {
    id: 'eeg',
    titel: 'Gesetz für den Ausbau erneuerbarer Energien (Erneuerbare-Energien-Gesetz)',
    herausgeber: 'Bundesministerium der Justiz / Bundesamt für Justiz',
    kennung: 'EEG 2023',
    ausgabe: '2022, zuletzt geändert 2025',
    url: 'https://www.gesetze-im-internet.de/eeg_2014/',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  gebaeudeenergiegesetz: {
    id: 'gebaeudeenergiegesetz',
    titel: 'Gesetz zur Einsparung von Energie und zur Nutzung erneuerbarer Energien zur Wärme- und Kälteerzeugung in Gebäuden (Gebäudeenergiegesetz)',
    herausgeber: 'Bundesministerium der Justiz / Bundesamt für Justiz',
    kennung: 'GEG',
    ausgabe: '2020, zuletzt geändert 2024',
    url: 'https://www.gesetze-im-internet.de/geg/',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },

  // --- Arbeits- und Sozialrecht (Wirtschafts- und Sozialkunde) -------------
  arbzg: {
    id: 'arbzg',
    titel: 'Arbeitszeitgesetz',
    herausgeber: 'Bundesministerium der Justiz / Bundesamt für Justiz',
    kennung: 'ArbZG',
    ausgabe: '1994, zuletzt geändert 2020',
    url: 'https://www.gesetze-im-internet.de/arbzg/',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  jarschg: {
    id: 'jarschg',
    titel: 'Gesetz zum Schutze der arbeitenden Jugend (Jugendarbeitsschutzgesetz)',
    herausgeber: 'Bundesministerium der Justiz / Bundesamt für Justiz',
    kennung: 'JArbSchG',
    ausgabe: '1976, zuletzt geändert 2022',
    url: 'https://www.gesetze-im-internet.de/jarbschg/',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  betrvg: {
    id: 'betrvg',
    titel: 'Betriebsverfassungsgesetz',
    herausgeber: 'Bundesministerium der Justiz / Bundesamt für Justiz',
    kennung: 'BetrVG',
    ausgabe: '1972, zuletzt geändert 2024',
    url: 'https://www.gesetze-im-internet.de/betrvg/',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  bdsg: {
    id: 'bdsg',
    titel: 'Bundesdatenschutzgesetz',
    herausgeber: 'Bundesministerium der Justiz / Bundesamt für Justiz',
    kennung: 'BDSG, ergänzend DSGVO (VO (EU) 2016/679)',
    ausgabe: '2017, zuletzt geändert 2024',
    url: 'https://www.gesetze-im-internet.de/bdsg_2018/',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  sgb4: {
    id: 'sgb4',
    titel: 'Sozialgesetzbuch (SGB) Viertes Buch – Gemeinsame Vorschriften für die Sozialversicherung',
    herausgeber: 'Bundesministerium der Justiz / Bundesamt für Justiz',
    kennung: 'SGB IV',
    ausgabe: '1976, zuletzt geändert 2025',
    url: 'https://www.gesetze-im-internet.de/sgb_4/',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  dguv1: {
    id: 'dguv1',
    titel: 'Grundsätze der Prävention (Unfallverhütungsvorschrift)',
    herausgeber: 'Deutsche Gesetzliche Unfallversicherung (DGUV)',
    kennung: 'DGUV Vorschrift 1',
    ausgabe: '2013-11',
    url: 'https://publikationen.dguv.de/regelwerk/dguv-vorschriften/11772/grundsaetze-der-praevention',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  // Achtung bei der Nummerierung: DGUV Vorschrift 4 ist – je nach
  // Unfallversicherungsträger – „Elektrische Anlagen und Betriebsmittel" (wie
  // Vorschrift 3). Die „Arbeitsmedizinische Vorsorge" trägt die Nummer 7 und
  // ist hier bewusst nicht hinterlegt.
  dguv4: {
    id: 'dguv4',
    titel: 'Elektrische Anlagen und Betriebsmittel (Unfallverhütungsvorschrift)',
    herausgeber: 'Deutsche Gesetzliche Unfallversicherung (DGUV)',
    kennung: 'DGUV Vorschrift 4 (früher GUV-V A 3)',
    ausgabe: '1997-01',
    url: 'https://publikationen.dguv.de/regelwerk/dguv-vorschriften/1457/elektrische-anlagen-und-betriebsmittel',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
  arbeitsschutzgesetz: {
    id: 'arbeitsschutzgesetz',
    titel: 'Gesetz über die Durchführung von Maßnahmen des Arbeitsschutzes zur Verbesserung der Sicherheit und des Gesundheitsschutzes der Beschäftigten bei der Arbeit (Arbeitsschutzgesetz)',
    herausgeber: 'Bundesministerium der Justiz / Bundesamt für Justiz',
    kennung: 'ArbSchG',
    ausgabe: '1996, zuletzt geändert 2024',
    url: 'https://www.gesetze-im-internet.de/arbschg/',
    abgerufen: ABGERUFEN,
    geprueft: true,
  },
};

/** Anzahl der am Original geprüften Quellen – für den Bericht. */
export function quellenBericht(): { gesamt: number; geprueft: number; offeneIds: string[] } {
  const alle = Object.values(QUELLEN);
  const offen = alle.filter((q) => !q.geprueft);
  return {
    gesamt: alle.length,
    geprueft: alle.length - offen.length,
    offeneIds: offen.map((q) => q.id),
  };
}
